#!/usr/bin/env python 

## This file was auto-generated by run.py called with the following arguments:
# run.py --platform Local --nbnodes 1 --whichSim stim_all_model --nbcpu 10 --scalefactor 1 1

## ID string of experiment:
# 2020_11_27_12_37_49_xp000000

## Reproducibility info:
#  platform = Local
#  git commit ID not available
#  Git status not available

connParams =\
{
    "BG": {
        "TH": [
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.9,
                            "sigma_x": 0.13,
                            "sigma_y": 0.13
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": -70.0
                },
                "post": [
                    "TH_M1_IZ",
                    "thalamic_nucleus_TC"
                ],
                "pre": "GPi_fake"
            }
        ]
    },
    "CB": {
        "TH": [
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 2.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 1.0,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.05
                },
                "post": [
                    "TH_S1_EZ",
                    "thalamic_nucleus_TC"
                ],
                "pre": "CB_S1_layer_vn"
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 2.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 1.0,
                            "sigma_x": 0.2,
                            "sigma_y": 0.2
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.05
                },
                "post": [
                    "TH_S1_EZ",
                    "thalamic_nucleus_IN"
                ],
                "pre": "CB_S1_layer_vn"
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 2.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 1.0,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 1.0
                },
                "post": [
                    "TH_M1_EZ",
                    "thalamic_nucleus_TC"
                ],
                "pre": "CB_M1_layer_vn"
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 2.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 1.0,
                            "sigma_x": 0.5,
                            "sigma_y": 0.5
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.1
                },
                "post": [
                    "TH_M1_EZ",
                    "thalamic_nucleus_IN"
                ],
                "pre": "CB_M1_layer_vn"
            }
        ]
    },
    "M1": {
        "CB": [
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.08,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 5.0
                },
                "post": "CB_M1_layer_pons",
                "pre": "M1_L5B_PT"
            }
        ],
        "S1": [],
        "TH": [
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.01
                },
                "post": [
                    "TH_M1_EZ",
                    "thalamic_nucleus_TC"
                ],
                "pre": "M1_L6_CT"
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.01
                },
                "post": [
                    "TH_M1_IZ",
                    "thalamic_nucleus_TC"
                ],
                "pre": "M1_L6_CT"
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 1.0,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.01
                },
                "post": [
                    "TH_M1_EZ",
                    "thalamic_reticular_neucleus_RE"
                ],
                "pre": "M1_L6_CT"
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 1.0,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.01
                },
                "post": [
                    "TH_M1_IZ",
                    "thalamic_reticular_neucleus_RE"
                ],
                "pre": "M1_L6_CT"
            }
        ]
    },
    "S1": {
        "CB": [
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.08,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 4.0
                },
                "post": "CB_S1_layer_pons",
                "pre": "S1_L5B_Pyr"
            }
        ],
        "M1": [],
        "TH": [
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.01
                },
                "post": [
                    "TH_S1_EZ",
                    "thalamic_nucleus_TC"
                ],
                "pre": "S1_L6_Pyr"
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.01
                },
                "post": [
                    "TH_S1_IZ",
                    "thalamic_nucleus_TC"
                ],
                "pre": "S1_L6_Pyr"
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 1.0,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.01
                },
                "post": [
                    "TH_S1_EZ",
                    "thalamic_reticular_neucleus_RE"
                ],
                "pre": "S1_L6_Pyr"
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 1.0,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.01
                },
                "post": [
                    "TH_S1_IZ",
                    "thalamic_reticular_neucleus_RE"
                ],
                "pre": "S1_L6_Pyr"
            }
        ]
    },
    "TH": {
        "M1": [
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.1
                },
                "post": "M1_L5B_PT",
                "pre": [
                    "TH_M1_EZ",
                    "thalamic_nucleus_TC"
                ]
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.1
                },
                "post": "M1_L5B_PT",
                "pre": [
                    "TH_M1_IZ",
                    "thalamic_nucleus_TC"
                ]
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.1
                },
                "post": "M1_L5B_PV",
                "pre": [
                    "TH_M1_EZ",
                    "thalamic_nucleus_TC"
                ]
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.1
                },
                "post": "M1_L5B_PV",
                "pre": [
                    "TH_M1_IZ",
                    "thalamic_nucleus_TC"
                ]
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.1
                },
                "post": "M1_L5B_SST",
                "pre": [
                    "TH_M1_EZ",
                    "thalamic_nucleus_TC"
                ]
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.1
                },
                "post": "M1_L5B_SST",
                "pre": [
                    "TH_M1_IZ",
                    "thalamic_nucleus_TC"
                ]
            }
        ],
        "S1": [
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.1
                },
                "post": "S1_L5B_Pyr",
                "pre": [
                    "TH_S1_EZ",
                    "thalamic_nucleus_TC"
                ]
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.1
                },
                "post": "S1_L5B_Pyr",
                "pre": [
                    "TH_S1_IZ",
                    "thalamic_nucleus_TC"
                ]
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.1
                },
                "post": "S1_L5B_PV",
                "pre": [
                    "TH_S1_EZ",
                    "thalamic_nucleus_TC"
                ]
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.1
                },
                "post": "S1_L5B_PV",
                "pre": [
                    "TH_S1_IZ",
                    "thalamic_nucleus_TC"
                ]
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.1
                },
                "post": "S1_L5B_SST",
                "pre": [
                    "TH_S1_EZ",
                    "thalamic_nucleus_TC"
                ]
            },
            {
                "conn_dict": {
                    "connection_type": "divergent",
                    "delays": 10.0,
                    "kernel": {
                        "gaussian2D": {
                            "p_center": 0.2,
                            "sigma_x": 0.1,
                            "sigma_y": 0.1
                        }
                    },
                    "mask": {
                        "box": {
                            "lower_left": [
                                -0.5,
                                -0.5,
                                -0.5
                            ],
                            "upper_right": [
                                0.5,
                                0.5,
                                0.5
                            ]
                        }
                    },
                    "weights": 0.1
                },
                "post": "S1_L5B_SST",
                "pre": [
                    "TH_S1_IZ",
                    "thalamic_nucleus_TC"
                ]
            }
        ]
    }
}